drop table t_lancamento;
drop table t_conta;
drop table t_tipo_lancamento;
drop table t_tipo_investimento;
drop table t_usuario;
drop SEQUENCE SEQ_CONTA;
drop SEQUENCE SEQ_LANCAMENTO;
drop SEQUENCE SEQ_TIPO_INVESTIMENTO;
drop SEQUENCE SEQ_TIPO_LANCAMENTO;
drop SEQUENCE SEQ_USUARIO;

-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-10-18 19:10:35 BRT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE t_conta (
    cd_conta   INTEGER NOT NULL,
    vl_agencia VARCHAR2(10 CHAR) NOT NULL,
    vl_conta   VARCHAR2(15 CHAR) NOT NULL,
    vl_banco   VARCHAR2(4 CHAR) NOT NULL,
    cd_usuario INTEGER
);

ALTER TABLE t_conta ADD CONSTRAINT cnt_pk PRIMARY KEY ( cd_conta );

CREATE TABLE t_lancamento (
    cd_lancamento        INTEGER NOT NULL,
    vl_lancamento        NUMBER(10, 2) NOT NULL,
    dt_lancamento        DATE NOT NULL,
    ds_lancamento        VARCHAR2(50 CHAR) NOT NULL,
    cd_tipo              INTEGER NOT NULL,
    cd_usuario           INTEGER,
    cd_conta             INTEGER NOT NULL,
    cd_tipo_investimento INTEGER
);

ALTER TABLE t_lancamento ADD CONSTRAINT lcto_pk PRIMARY KEY ( cd_lancamento );

CREATE TABLE t_tipo_investimento (
    cd_tipo_investimento      INTEGER NOT NULL,
    ds_tipo_investimento      VARCHAR2(255 CHAR) NOT NULL,
    vl_rendimento_mensal      NUMBER(10, 2) NOT NULL,
    prazo_minimo_investimento INTEGER
);

ALTER TABLE t_tipo_investimento ADD CONSTRAINT tp_invest_pk PRIMARY KEY ( cd_tipo_investimento );

CREATE TABLE t_tipo_lancamento (
    cd_tipo INTEGER NOT NULL,
    ds_tipo VARCHAR2(100 CHAR) NOT NULL
);

ALTER TABLE t_tipo_lancamento ADD CONSTRAINT tp_lcto_pk PRIMARY KEY ( cd_tipo );

CREATE TABLE t_usuario (
    cd_usuario       INTEGER NOT NULL,
    vl_cpf_usuario   CHAR(11) NOT NULL,
    ds_senha         VARCHAR2(100) NOT NULL,
    nm_usuario       VARCHAR2(150) NOT NULL,
    ck_usuario_ativo NUMBER NOT NULL
);

ALTER TABLE t_usuario ADD CONSTRAINT usu_pk PRIMARY KEY ( cd_usuario );

ALTER TABLE t_lancamento
    ADD CONSTRAINT rel_lcto_cnt_fk FOREIGN KEY ( cd_conta )
        REFERENCES t_conta ( cd_conta );

ALTER TABLE t_lancamento
    ADD CONSTRAINT rel_lcto_tp_invest_fk FOREIGN KEY ( cd_tipo_investimento )
        REFERENCES t_tipo_investimento ( cd_tipo_investimento );

ALTER TABLE t_lancamento
    ADD CONSTRAINT rel_lcto_tp_lcto_fk FOREIGN KEY ( cd_tipo )
        REFERENCES t_tipo_lancamento ( cd_tipo );

ALTER TABLE t_lancamento
    ADD CONSTRAINT rel_lcto_usu_fk FOREIGN KEY ( cd_usuario )
        REFERENCES t_usuario ( cd_usuario );

ALTER TABLE t_conta
    ADD CONSTRAINT t_conta_t_usuario_fk FOREIGN KEY ( cd_usuario )
        REFERENCES t_usuario ( cd_usuario );

CREATE SEQUENCE SEQ_CONTA NOCACHE;
CREATE SEQUENCE SEQ_LANCAMENTO NOCACHE;
CREATE SEQUENCE SEQ_TIPO_INVESTIMENTO NOCACHE;
CREATE SEQUENCE SEQ_TIPO_LANCAMENTO NOCACHE;
CREATE SEQUENCE SEQ_USUARIO NOCACHE;